### ISSUE TITLE
No items in RSS feeds

### ISSUE THREAD

**Issue by aragilar** [pmelchior/aas2rss#1]
The RSS feeds seem to be empty, is the code still working?

**Comment by pmelchior** [comment]
I haven't noticed any problems (but I could easily have missed them). Which category is not working for you? Even better, can you find a post on http://jobregister.aas.org that isn't listed in the feed?

**Comment by aragilar** [comment]
Found the problem, issue is Firefox seems fairly strict with RSS feeds (so probably something in https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Faas2rss.pmelchior.net%2Faas2rss.php%3Fchannel%3Dfaculty_visiting is why Firefox isn't working).
This isn't a big issue for me as I use a different rss reader (newsbeuter) which seems to deal with the content fine (by appearing to ignore the html). Maybe add a warning about the feed appearing empty in Firefox on the home page?

**Comment by pmelchior** [comment]
Thanks for the link. I set the ContentType, so that browsers should show the pages now (Chrome does, I don't have Firefox to test right now). However, the underlying problem is how to treat HTML tags in RSS, and that has a bit of a history (e.g. http://stackoverflow.com/questions/9866472/rss-specification-html-code-inside-rss-feed).

As much as I would like to implement something that validates, I am content with something that shows up correctly in readers.
